server:
  port: 8081
spring:
  application:
    name: user-auth-service
  datasource:
    url: jdbc:mysql://localhost:3306/ecommerce_db?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC
    username: root
    password: password
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    open-in-view: false
    properties:
      hibernate.format_sql: true
      hibernate.jdbc.time_zone: UTC
#  flyway:
#    enabled: true
#    locations: classpath:db/migration

#security:
#  jwt:
#    issuer: ecommerce-auth
#    access-token-minutes: 15
#    refresh-token-days: 7
#    rsa:
#      public-key: classpath:keystore/public.pem
#      private-key: classpath:keystore/private.pem

logging:
  level:
    root: INFO
    org.springframework.security: INFO
    com.acme.auth: DEBUG